### ISSUE TITLE
Problème avec les quêtes où il faut tuer des monstres.

### ISSUE THREAD

**Issue by Kyraito2** [SkytAsul/BeautyQuests#118]
**Describe the bug**	
Bonjour ! Nous avons remarqué depuis quelque jours que les quêtes où il faut tuer des monstres avaient un problème: Parfois, lorsqu'un monstre spécifique doit être tuer pour compléter une quête, la quête se complète lorsque le joueur tue un autre monstre complètement différent. 

En fouillant dans les logs, j'ai trouvé que deux quêtes, toutes deux nécéssitant de tuer des monstres, généraient des erreurs. Je les ai listées plus bas. 

**Reproduction**
Nous avons tenté de reproduire le problème artificiellement sans succès. Il est cependant arrivé plus d'une fois par hasard. Nous essayons toujours de le reproduire. 

**Screenshots, error messages**
```
[06:09:19] [Server thread/ERROR]: [BeautyQuests] Error when deserializing the branch 0 for the quest Ouaaaaaf ! (false return)
[06:09:19] [Server thread/ERROR]: [BeautyQuests] Quest from file 15.yml not activated
[06:09:19] [Server thread/INFO]: [BeautyQuests] Error when loading quest. Creating backup...
[06:09:19] [Server thread/INFO]: [BeautyQuests] Quest backup created at 15-backup2020-05-04-06-09-19.yml
[06:09:19] [Server thread/ERROR]: [BeautyQuests] Error when deserializing the stage 0 for the quest La fleure d'Élésia
[06:09:19] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[06:09:19] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:09:19] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:09:19] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:09:19] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.api.stages.AbstractStage.deserialize(AbstractStage.java:234)
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.structure.QuestBranch.load(QuestBranch.java:296)
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.structure.BranchesManager.deserialize(BranchesManager.java:183)
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.structure.Quest.deserialize(Quest.java:518)
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.structure.Quest.loadFromFile(Quest.java:498)
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.BeautyQuests.loadAllDatas(BeautyQuests.java:322)
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.BeautyQuests.access$000(BeautyQuests.java:50)
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.BeautyQuests$1.run(BeautyQuests.java:114)
[06:09:19] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[06:09:19] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[06:09:19] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[06:09:19] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399)
[06:09:19] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[06:09:19] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[06:09:19] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[06:09:19] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.utils.Utils.deserializeList(Utils.java:319)
[06:09:19] [Server thread/WARN]: at fr.skytasul.quests.stages.StageMobs.deserialize(StageMobs.java:234)
[06:09:19] [Server thread/WARN]: ... 19 more
[06:09:19] [Server thread/ERROR]: [BeautyQuests] Error when deserializing the branch 0 for the quest La fleure d'Élésia (false return)
[06:09:19] [Server thread/ERROR]: [BeautyQuests] Quest from file 11.yml not activated
[06:09:19] [Server thread/INFO]: [BeautyQuests] Error when loading quest. Creating backup...
[06:09:19] [Server thread/INFO]: [BeautyQuests] Quest backup created at 11-backup2020-05-04-06-09-19.yml
[06:09:19] [Server thread/INFO]: [BeautyQuests] 9 quests loaded (0.031s)!
```

**Software**
BeautyQuests version: 1.61.2
Game version: 1.15.2
Server version: 1.15.2
Server type (e.i. PaperSpigot): Spigot
Are you using a protocol hack (like ViaVersion)? Nope

**Additional context (optional)**
N/A

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
J'ai réécrit le code relatif aux stage monstres dans la 0.17. Elle est toujours en pre-release, mais tu peux trouver les dev builds [ici](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/) !

**Comment by Kyraito2** [comment]
J'avais essayé de passer sur la dev build quelques jours plus tôt, mais là les quêtes de monstres ne fonctionnaient tout simplement pas. Je vais réessayer maintenant, merci ! ^^

**Comment by SkytAsul** [comment]
Mmh c'est possible que tes données actuelles soient corrompues et donc qu'elles n'arrivent pas à être upgrade... essaye de mettre la dev build et vois si il y a des erreurs au chargmenet.

**Comment by Kyraito2** [comment]
Yup ça m'a l'air réglé. :D

**Comment by SkytAsul** [comment]
Parfait ^^
