### ISSUE TITLE
Mythicmobs and quest causing an issue

### ISSUE THREAD

**Issue by karuney** [SkytAsul/BeautyQuests#130]
I am trying to make a simple kill quest to kill a mythicmobs (1 kill) and it is giving me this error:

> [14-Jul-2020 17:53:57] [WARN] [BeautyQuests] Task #1482 for BeautyQuests v0.17.3 generated an exception

[14-Jul-2020 17:53:57] java.lang.NullPointerException: null

[14-Jul-2020 17:53:57] at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs.getName(MythicMobs.java:56) ~[?:?]

[14-Jul-2020 17:53:57] at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs.getName(MythicMobs.java:23) ~[?:?]

[14-Jul-2020 17:53:57] at fr.skytasul.quests.api.mobs.Mob.getName(Mob.java:29) ~[?:?]

[14-Jul-2020 17:53:57] at fr.skytasul.quests.api.mobs.Mob.createItemStack(Mob.java:38) ~[?:?]

[14-Jul-2020 17:53:57] at fr.skytasul.quests.gui.mobs.MobsListGUI$1.lambda$null$0(MobsListGUI.java:88) ~[?:?]

[14-Jul-2020 17:53:57] at fr.skytasul.quests.editors.TextEditor.chat(TextEditor.java:78) ~[?:?]

[14-Jul-2020 17:53:57] at fr.skytasul.quests.editors.Editor.callChat(Editor.java:69) ~[?:?]

[14-Jul-2020 17:53:57] at fr.skytasul.quests.editors.Editor.lambda$onChat$0(Editor.java:83) ~[?:?]

[14-Jul-2020 17:53:57] at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2-2692.jar:git-Spigot-a99063f-fad2494]

[14-Jul-2020 17:53:57] at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2-2692.jar:git-Spigot-a99063f-fad2494]

[14-Jul-2020 17:53:57] at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2-2692.jar:git-Spigot-a99063f-fad2494]

[14-Jul-2020 17:53:57] at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2-2692.jar:git-Spigot-a99063f-fad2494]

[14-Jul-2020 17:53:57] at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2-2692.jar:git-Spigot-a99063f-fad2494]

[14-Jul-2020 17:53:57] at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2-2692.jar:git-Spigot-a99063f-fad2494]

[14-Jul-2020 17:53:57] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by SkytAsul** [comment]
Which version of MythicMobs are you using?

**Comment by karuney** [comment]
4.9.1-3295

**Comment by SkytAsul** [comment]
Fixed with https://github.com/SkytAsul/BeautyQuests/commit/9a366a0ea266fb94a2da1db789acbacd94a959f1 - thanks for reporting!
