### ISSUE TITLE
First Quest doesn't load for players

### ISSUE THREAD

**Issue by ChibiMango** [SkytAsul/BeautyQuests#151]
**Describe the bug**	
I am trying to assign a starting quest for players who first join, but it doesn't actually give them a quest and shows an error in chat.

**Reproduction**

**Screenshots, error messages**
[22:24:33 ERROR]: Could not pass event PlayerAccountJoinEvent to BeautyQuests v0.18.5
java.lang.NullPointerException: null
        at fr.skytasul.quests.structure.BranchesManager.startPlayer(BranchesManager.java:85) ~[?:?]
        at fr.skytasul.quests.structure.Quest$1.run(Quest.java:291) ~[?:?]
        at fr.skytasul.quests.structure.Quest.start(Quest.java:299) ~[?:?]
        at fr.skytasul.quests.QuestsListener.onAccountJoin(QuestsListener.java:115) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor516.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-294]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-294]
        at fr.skytasul.quests.QuestsListener.lambda$2(QuestsListener.java:107) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-294]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Software**
BeautyQuests version: 0.18.5
Game version: 1.16.4
Server version: 1.16.5
Server type (e.i. PaperSpigot): PaperSpigot
Are you using a protocol hack (like ViaVersion)? No

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by EnderGriefeur99** [comment]
try this version https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/189/artifact/target/beautyquests-0.19.0-SNAPSHOT.jar

**Comment by SkytAsul** [comment]
Must be fixed.
