### ISSUE TITLE
Scoreboard error

### ISSUE THREAD

**Issue by teon56** [SkytAsul/BeautyQuests#169]
Quand on veut affiché le scoreboard une erreur ce produit 

Lorsque je lance une quête le scoreboard ne s'affiche pas, en faisant /quest scoreboard show cette erreur ce produit avec dans le chat : Code d'erreur : NoClasseDefFoundError

[20:47:36 WARN]: java.lang.reflect.InvocationTargetException
[20:47:36 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:47:36 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[20:47:36 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:47:36 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[20:47:36 WARN]: 	at fr.skytasul.quests.commands.CommandsManager.onCommand(CommandsManager.java:135)
[20:47:36 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:47:36 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[20:47:36 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:825)
[20:47:36 WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[20:47:36 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1996)
[20:47:36 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1977)
[20:47:36 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[20:47:36 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[20:47:36 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[20:47:36 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:47:36 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[20:47:36 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[20:47:36 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340)
[20:47:36 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[20:47:36 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[20:47:36 WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319)
[20:47:36 WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312)
[20:47:36 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[20:47:36 WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273)
[20:47:36 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184)
[20:47:36 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[20:47:36 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[20:47:36 WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class fr.skytasul.quests.scoreboards.FastBoard
[20:47:36 WARN]: 	at fr.skytasul.quests.scoreboards.Scoreboard.initScoreboard(Scoreboard.java:256)
[20:47:36 WARN]: 	at fr.skytasul.quests.scoreboards.Scoreboard.show(Scoreboard.java:166)
[20:47:36 WARN]: 	at fr.skytasul.quests.commands.Commands.scoreboard(Commands.java:437)
[20:47:36 WARN]: 	... 27 more

BeautyQuests version: 0.19 dev build #224
Game version: 1.17
Server version: 1.17
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? Non

**Additional context (optional)**

**Comment by SkytAsul** [comment]
Fixé avec #d0a4786
