### ISSUE TITLE
Erreur avec le quest list

### ISSUE THREAD

**Issue by teon56** [SkytAsul/BeautyQuests#170]
Losque l'on effectue la commande /quest list 

En entrant la commande /quest list on as dans le chat l'erreur Code d'erreur : NoSuchMethodError

21:09:50 WARN]: java.lang.reflect.InvocationTargetException
[21:09:50 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:09:50 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[21:09:50 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:09:50 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[21:09:50 WARN]: 	at fr.skytasul.quests.commands.CommandsManager.onCommand(CommandsManager.java:135)
[21:09:50 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:09:50 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:09:50 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:825)
[21:09:50 WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[21:09:50 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1996)
[21:09:50 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1977)
[21:09:50 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[21:09:50 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[21:09:50 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[21:09:50 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:09:50 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[21:09:50 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[21:09:50 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340)
[21:09:50 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[21:09:50 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[21:09:50 WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319)
[21:09:50 WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312)
[21:09:50 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[21:09:50 WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273)
[21:09:50 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184)
[21:09:50 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:09:50 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[21:09:50 WARN]: Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.server.network.PlayerConnection.a(net.minecraft.network.protocol.Packet)'
[21:09:50 WARN]: 	at fr.skytasul.quests.utils.nms.v1_17_R1.sendPacket(v1_17_R1.java:40)
[21:09:50 WARN]: 	at fr.skytasul.quests.utils.Utils.openBook(Utils.java:66)
[21:09:50 WARN]: 	at fr.skytasul.quests.gui.misc.ListBook.openQuestBook(ListBook.java:45)
[21:09:50 WARN]: 	at fr.skytasul.quests.commands.Commands.list(Commands.java:386)
[21:09:50 WARN]: 	... 27 more

**Software**
BeautyQuests version: 0.19 dev build #225:
Game version: 1.17
Server version: 1.17
Server type (e.i. PaperSpigot): paper
Are you using a protocol hack (like ViaVersion)? non

**Comment by SkytAsul** [comment]
Fixed with dev build #228: https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/228/artifact/target/beautyquests-0.19.0-SNAPSHOT.jar
