### ISSUE TITLE
Scoreboard qui ne se met pas a jour 

### ISSUE THREAD

**Issue by teon56** [SkytAsul/BeautyQuests#171]
Lors du passage d'une étape de quête le scoreboard ne se met pas a jour

Réaliser une étape de quête

[21:11:59 WARN]: [BeautyQuests] Task #9433 for BeautyQuests v0.19.0_BUILD225 generated an exception
fr.skytasul.quests.utils.ParticleEffect$ParticlePacket$PacketSendingException: Failed to send the packet to player 'teon56'
	at fr.skytasul.quests.utils.ParticleEffect$ParticlePacket.sendTo(ParticleEffect.java:860) ~[?:?]
	at fr.skytasul.quests.utils.ParticleEffect$ParticlePacket.sendTo(ParticleEffect.java:876) ~[?:?]
	at fr.skytasul.quests.utils.ParticleEffect.display(ParticleEffect.java:275) ~[?:?]
	at fr.skytasul.quests.utils.ParticleEffect$Particle.sendParticle(ParticleEffect.java:646) ~[?:?]
	at fr.skytasul.quests.utils.ParticleEffect$Particle.send(ParticleEffect.java:632) ~[?:?]
	at fr.skytasul.quests.structure.QuestBranch.setStage(QuestBranch.java:220) ~[?:?]
	at fr.skytasul.quests.structure.QuestBranch.start(QuestBranch.java:142) ~[?:?]
	at fr.skytasul.quests.structure.QuestBranch.lambda$finishStage$1(QuestBranch.java:178) ~[?:?]
	at fr.skytasul.quests.structure.QuestBranch.endStage(QuestBranch.java:199) ~[?:?]
	at fr.skytasul.quests.structure.QuestBranch.finishStage(QuestBranch.java:157) ~[?:?]
	at fr.skytasul.quests.api.stages.AbstractStage.finishStage(AbstractStage.java:155) ~[?:?]
	at fr.skytasul.quests.stages.StageChat.lambda$check$0(StageChat.java:79) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:476) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.server.network.PlayerConnection.a(net.minecraft.network.protocol.Packet)'
	at fr.skytasul.quests.utils.nms.v1_17_R1.sendPacket(v1_17_R1.java:40) ~[?:?]
	at fr.skytasul.quests.utils.ParticleEffect$ParticlePacket.sendTo(ParticleEffect.java:855) ~[?:?]
	... 19 more

**Software**
BeautyQuests version: 0.19 dev build #225:
Game version: 1.17
Server version: 1.17
Server type (e.i. PaperSpigot): paper
Are you using a protocol hack (like ViaVersion)? non

![New Project (15)](https://user-images.githubusercontent.com/1591362/122685646-08dc5f80-d20d-11eb-9574-84c0ef5b233d.png)

**Comment by SkytAsul** [comment]
Fixed with dev build #228: https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/228/artifact/target/beautyquests-0.19.0-SNAPSHOT.jar
