### ISSUE TITLE
Error appear randomly 

### ISSUE THREAD

**Issue by teon56** [SkytAsul/BeautyQuests#172]
Cette erreur apparait de façon aléatoire 

[18:05:52 WARN]: [BeautyQuests] Task #14660 for BeautyQuests v0.19.0_BUILD228 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: No field with type [I exists in class PacketPlayOutEntityDestroy.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityDestroy.setEntities(WrapperPlayServerEntityDestroy.java:51) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityDestroy.setEntities(WrapperPlayServerEntityDestroy.java:59) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.PacketHelper.sendDestroyEntitiesPacket(PacketHelper.java:132) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.sendDestroyEntitiesPacket(ProtocolLibHookImpl.java:218) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftVisibilityManager.sendDestroyPacketIfNear(CraftVisibilityManager.java:172) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftVisibilityManager.hideTo(CraftVisibilityManager.java:106) ~[?:?]
	at fr.skytasul.quests.utils.compatibility.BQHolographicDisplays$HDHologram.setPlayersVisible(BQHolographicDisplays.java:66) ~[?:?]
	at fr.skytasul.quests.structure.NPCStarter$Hologram.setVisible(NPCStarter.java:273) ~[?:?]
	at fr.skytasul.quests.structure.NPCStarter$2.run(NPCStarter.java:117) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:476) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Software**
BeautyQuests version: 0.19 dev build #228:
Game version: 1.17
Server version: 1.17
Server type (e.i. PaperSpigot): paper
Are you using a protocol hack (like ViaVersion)? non

**Comment by EnderGriefeur99** [comment]
c'est ton protocollib qui n'est pas encore 100% a jour

**Comment by teon56** [comment]
Ok, j'ai installer la dernière devbuild de protocolibs mais je vais attendre de prochaines Maj
