### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by elmundomusical2** [SkytAsul/BeautyQuests#182]
**Describe the bug**	
```
[12:37:34 WARN]: java.lang.NullPointerException: Cannot invoke "fr.skytasul.quests.players.PlayersManager.save()" because "fr.skytasul.quests.players.PlayersManager.manager" is null
[12:37:34 WARN]:        at fr.skytasul.quests.BeautyQuests.saveAllConfig(BeautyQuests.java:493)
[12:37:34 WARN]:        at fr.skytasul.quests.BeautyQuests.onDisable(BeautyQuests.java:219)
[12:37:34 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[12:37:34 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405)
[12:37:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533)
[12:37:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519)
[12:37:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512)
[12:37:34 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:452)
[12:37:34 WARN]:        at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:1023)
[12:37:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:817)
[12:37:34 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1317)
[12:37:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[12:37:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Reproduction**
When the server starts

**Screenshots, error messages**
Are there error messages in the console or in the chat?

**Software**
BeautyQuests version: 0.19.0-SNAPSHOT
Game version: 1.17
Server version: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Windows 10 10.0 (amd64)
Server type (e.i. PaperSpigot): Paper

**Comment by SkytAsul** [comment]
There must be another error before this one. Please send me your complete server log.

**Comment by Al3ks19** [comment]
[23:34:02 INFO]: Aleks19 issued server command: /quest scoreboard Aleks19 show
[23:34:02 WARN]: java.lang.reflect.InvocationTargetException
[23:34:02 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:34:02 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[23:34:02 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:34:02 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[23:34:02 WARN]: 	at fr.skytasul.quests.commands.CommandsManager.onCommand(CommandsManager.java:136)
[23:34:02 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:34:02 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:34:02 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[23:34:02 WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[23:34:02 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1996)
[23:34:02 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1977)
[23:34:02 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[23:34:02 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[23:34:02 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[23:34:02 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:34:02 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[23:34:02 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[23:34:02 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340)
[23:34:02 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[23:34:02 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[23:34:02 WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319)
[23:34:02 WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312)
[23:34:02 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[23:34:02 WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273)
[23:34:02 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184)
[23:34:02 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[23:34:02 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[23:34:02 WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class fr.skytasul.quests.scoreboards.FastBoard
[23:34:02 WARN]: 	at fr.skytasul.quests.scoreboards.Scoreboard.initScoreboard(Scoreboard.java:243)
[23:34:02 WARN]: 	at fr.skytasul.quests.scoreboards.Scoreboard.show(Scoreboard.java:153)
[23:34:02 WARN]: 	at fr.skytasul.quests.commands.Commands.scoreboard(Commands.java:417)
[23:34:02 WARN]: 	... 27 more
[23:34:05 WARN]: [fr.skytasul.quests.BeautyQuests] [BeautyQuests] Plugin BeautyQuests v0.18.5 generated an exception while executing task 4759
java.lang.NoClassDefFoundError: Could not initialize class fr.skytasul.quests.scoreboards.FastBoard
	at fr.skytasul.quests.scoreboards.Scoreboard.initScoreboard(Scoreboard.java:243) ~[?:?]
	at fr.skytasul.quests.scoreboards.Scoreboard.run(Scoreboard.java:74) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-43]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-43]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:34:15 WARN]: [fr.skytasul.quests.BeautyQuests] [BeautyQuests] Plugin BeautyQuests v0.18.5 generated an exception while executing task 4759
java.lang.NoClassDefFoundError: Could not initialize class fr.skytasul.quests.scoreboards.FastBoard
	at fr.skytasul.quests.scoreboards.Scoreboard.initScoreboard(Scoreboard.java:243) ~[?:?]
	at fr.skytasul.quests.scoreboards.Scoreboard.run(Scoreboard.java:74) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-43]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-43]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:34:21 INFO]: Aleks19 issued server command: /gamemode survival Aleks19
[23:34:25 WARN]: [fr.skytasul.quests.BeautyQuests] [BeautyQuests] Plugin BeautyQuests v0.18.5 generated an exception while executing task 4759
java.lang.NoClassDefFoundError: Could not initialize class fr.skytasul.quests.scoreboards.FastBoard
	at fr.skytasul.quests.scoreboards.Scoreboard.initScoreboard(Scoreboard.java:243) ~[?:?]
	at fr.skytasul.quests.scoreboards.Scoreboard.run(Scoreboard.java:74) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-43]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-43]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:34:26 INFO]: Aleks19 issued server command: /gamemode survival Aleks19
[23:34:31 INFO]: Aleks19 issued server command: /gamemode survival
[23:34:35 WARN]: [fr.skytasul.quests.BeautyQuests] [BeautyQuests] Plugin BeautyQuests v0.18.5 generated an exception while executing task 4759
java.lang.NoClassDefFoundError: Could not initialize class fr.skytasul.quests.scoreboards.FastBoard
	at fr.skytasul.quests.scoreboards.Scoreboard.initScoreboard(Scoreboard.java:243) ~[?:?]
	at fr.skytasul.quests.scoreboards.Scoreboard.run(Scoreboard.java:74) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-43]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-43]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:34:45 WARN]: [fr.skytasul.quests.BeautyQuests] [BeautyQuests] Plugin BeautyQuests v0.18.5 generated an exception while executing task 4759
java.lang.NoClassDefFoundError: Could not initialize class fr.skytasul.quests.scoreboards.FastBoard
	at fr.skytasul.quests.scoreboards.Scoreboard.initScoreboard(Scoreboard.java:243) ~[?:?]
	at fr.skytasul.quests.scoreboards.Scoreboard.run(Scoreboard.java:74) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-43]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-43]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:34:49 INFO]: Aleks19 issued server command: /gamemode creative Aleks19
[23:34:49 INFO]: [Aleks19: Set own game mode to Creative Mode]
[23:34:55 WARN]: [fr.skytasul.quests.BeautyQuests] [BeautyQuests] Plugin BeautyQuests v0.18.5 generated an exception while executing task 4759

**Comment by Al3ks19** [comment]
I have the same error, here is the complete error text

**Comment by Al3ks19** [comment]
Hello, I found the solution to the problem. After I installed the latest version, the error no longer appeared:

 https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/232/artifact/target/beautyquests-0.19.0-SNAPSHOT.jar

**Comment by SkytAsul** [comment]
@Al3ks19 yeah that's because you were using 0.18.5 on a 1.17 server.

However @elmundomusical2 is using 0.19 so idk. Try to update to the latest dev build. Also if it still occurs please send me the complete log file.

**Comment by SkytAsul** [comment]
I'm assuming this is fixed. Please reopen the issue otherwise.
