### ISSUE TITLE
Executing task 11349 Error

### ISSUE THREAD

**Issue by TimGraham777** [SkytAsul/BeautyQuests#203]
**Describe the bug**	
Console error message repeated.

**Reproduction**
Starts repeating after player connects.

**Screenshots, error messages**
[14.12 10:51:15] [Server] [WARN] [fr.skytasul.quests.BeautyQuests] [BeautyQuests] Plugin BeautyQuests v0.19.0_BUILD262 generated an exception while executing task 11349
[14.12 10:51:15] [Server] java.lang.NoClassDefFoundErrorCould not initialize class fr.skytasul.quests.scoreboards.FastBoard
[14.12 10:51:15] [Server]     at fr.skytasul.quests.scoreboards.Scoreboard.initScoreboard(Scoreboard.java:272) ~[beautyquests-0.19.0-SNAPSHOT.jar:?]
[14.12 10:51:15] [Server]     at fr.skytasul.quests.scoreboards.Scoreboard.run(Scoreboard.java:80) ~[beautyquests-0.19.0-SNAPSHOT.jar:?]
[14.12 10:51:15] [Server]     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-74]
[14.12 10:51:15] [Server]     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-74]
[14.12 10:51:15] [Server]     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-74]
[14.12 10:51:15] [Server]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
[14.12 10:51:15] [Server]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
[14.12 10:51:15] [Server]     at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Software**
BeautyQuests version: v0.19.0_BUILD26
Game version: 1.18.1
Server version: Paper 1.18.1-R0.1-SNAPSHOT
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? ViaVersion 4.1.1

**Comment by SkytAsul** [comment]
Dev build 262 is outdated. This bug has been fixed in a later dev build. Please do not open issue for bugs if you haven't tested it on latest version, thanks. https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/
