### ISSUE TITLE
spam WARN dans la console

### ISSUE THREAD

**Issue by thekepaag** [SkytAsul/BeautyQuests#210]
**Describe the bug**	
Il s'agit d'un spam de la console de WARN 

j'ai mis à jour ProtocolLibs et HolographicDisplay à leurs dernières versions. 

**Reproduction**
en boucle dans la console

**Screenshots, error messages**

[21:33:36] [Server thread/WARN]: java.lang.NoSuchFieldException: playersVisibilityMap
[21:33:36] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[21:33:36] [Server thread/WARN]: 	at beautyquests-0.19.0-SNAPSHOT.jar//fr.skytasul.quests.utils.compatibility.BQHolographicDisplays$HDHologram.setPlayersVisible(BQHolographicDisplays.java:55)
[21:33:36] [Server thread/WARN]: 	at beautyquests-0.19.0-SNAPSHOT.jar//fr.skytasul.quests.structure.NPCStarter$Hologram.setVisible(NPCStarter.java:278)
[21:33:36] [Server thread/WARN]: 	at beautyquests-0.19.0-SNAPSHOT.jar//fr.skytasul.quests.structure.NPCStarter$2.run(NPCStarter.java:120)
[21:33:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:33:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[21:33:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[21:33:36] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[21:33:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[21:33:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[21:33:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[21:33:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Software**
BeautyQuests version: 0.19
Game version:  1.18.1
Server version: paper 1.18.1
Server type (e.i. PaperSpigot): paper
Are you using a protocol hack (like ViaVersion)? non

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Ca a été fix dans une dev build suivant la 268. https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/lastSuccessfulBuild/
