### ISSUE TITLE
error in console causing server to crash after about 2 hours

### ISSUE THREAD

**Issue by Sepncer** [SkytAsul/BeautyQuests#222]
[12:01:45] [Craft Scheduler Thread - 254/WARN]: [BeautyQuests] Plugin BeautyQuests v0.18.5 generated an exception while executing task 163845
java.lang.NoClassDefFoundError: Could not initialize class fr.skytasul.quests.scoreboards.FastBoard
	at fr.skytasul.quests.scoreboards.Scoreboard.initScoreboard(Scoreboard.java:243) ~[?:?]
	at fr.skytasul.quests.scoreboards.Scoreboard.run(Scoreboard.java:74) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[server.jar:3284-a-Spigot-3892929-0ab8487]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:3284-a-Spigot-3892929-0ab8487]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

i have no clue how to reproduce this

**Comment by EnderGriefeur99** [comment]
You use an old version update the plugin please.
