### ISSUE TITLE
Mythic Mobs

### ISSUE THREAD

**Issue by RanggaGibran** [SkytAsul/BeautyQuests#246]
**Describe the bug**	
I want to add kill mythicmobs in quests, but I can't, the menu is there but it doesn't work.

**Reproduction**
1. Create Quests.
2. Stage 1 Dialog NPC
3. Stage 2 Kill Mobs MythicMobs (Error)

**Screenshots, error messages**

[20:32:50 ERROR]: Could not pass event InventoryClickEvent to BeautyQuests v0.19.7
java.lang.NoSuchMethodError: 'java.lang.String io.lumine.mythic.api.mobs.MythicMob.getEntityType()'
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5.getEntityType(MythicMobs5.java:86) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5$1.getItemStack(MythicMobs5.java:50) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5$1.getItemStack(MythicMobs5.java:45) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.gui.templates.PagedGUI.setItems(PagedGUI.java:107) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.gui.templates.PagedGUI.open(PagedGUI.java:72) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.gui.Inventories.create(Inventories.java:45) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.gui.CustomInventory.create(CustomInventory.java:53) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5.itemClick(MythicMobs5.java:63) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.gui.mobs.MobsListGUI$1.click(MobsListGUI.java:75) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.gui.mobs.MobsListGUI$1.click(MobsListGUI.java:68) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.gui.templates.PagedGUI.onClick(PagedGUI.java:176) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:78) ~[beautyquests-0.19.7.jar:?]
        at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:129) ~[beautyquests-0.19.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1032.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2861) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Software**
BeautyQuests version:
Game version: 0.19.7
Server version: 1.18.2
Server type (e.i. PaperSpigot): PaperSpigot
Are you using a protocol hack (like ViaVersion)? yes

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de 
![image_2022-11-28_033704483](https://user-images.githubusercontent.com/101553767/204158471-e1ffd885-e826-49cf-b453-8e7862cb8d94.png)
ma langue natale)

**Comment by SkytAsul** [comment]
Use latest dev build (https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/).

**Comment by RanggaGibran** [comment]
Thanks, it works very well
