### ISSUE TITLE
Mythicmobs bug

### ISSUE THREAD

**Issue by Crazall** [SkytAsul/BeautyQuests#250]
**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

Create new stage and choose "kill mobs"
![image](https://user-images.githubusercontent.com/105592292/207626312-95ebeae0-83aa-44ff-be76-4b3ba5319bf5.png)
Choose "Select Mythic Mob"
![image](https://user-images.githubusercontent.com/105592292/207626458-4349df81-2b20-48b6-85f5-87579e43da80.png)
Bad things happened, menu didn't open :( 
And cmd output an ERROR
![image](https://user-images.githubusercontent.com/105592292/207626928-fb7c5b4a-7876-408f-a47f-bf99f8ab266f.png)
`[22:45:24 ERROR]: [BeautyQuests] Cannot open inventory  to player Crealiest
java.lang.NoSuchMethodError: 'io.lumine.mythic.api.mobs.entities.MythicEntityType io.lumine.mythic.api.mobs.MythicMob.getEntityType()'
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5.getEntityType(MythicMobs5.java:97) ~[?:?]
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5$1.getItemStack(MythicMobs5.java:49) ~[?:?]
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5$1.getItemStack(MythicMobs5.java:44) ~[?:?]
        at fr.skytasul.quests.gui.templates.PagedGUI.setItems(PagedGUI.java:114) ~[?:?]
        at fr.skytasul.quests.gui.templates.PagedGUI.open(PagedGUI.java:73) ~[?:?]
        at fr.skytasul.quests.gui.Inventories.create(Inventories.java:46) ~[?:?]
        at fr.skytasul.quests.gui.CustomInventory.create(CustomInventory.java:53) ~[?:?]
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5.itemClick(MythicMobs5.java:62) ~[?:?]
        at fr.skytasul.quests.gui.mobs.MobSelectionGUI.click(MobSelectionGUI.java:33) ~[?:?]
        at fr.skytasul.quests.gui.mobs.MobSelectionGUI.click(MobSelectionGUI.java:17) ~[?:?]
        at fr.skytasul.quests.gui.templates.PagedGUI.onClick(PagedGUI.java:183) ~[?:?]
        at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:84) ~[?:?]
        at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:132) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1516.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-786]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
        at java.lang.Thread.run(Thread.java:831) [?:?]`
I was using MythicMobs 5.2.0 premium.
When I switch to BeautyQuests 0.19.7, this problem **didn't** show up.

**Software**
BeautyQuests version: 0.20.0
Game version: 1.16.5
Server version: paper-1.16.5-786
MythicMobs version: 5.2.0
Are you using a protocol hack (like ViaVersion)?
No
**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
You are not running latest MythicMobs version. I just downloaded 5.2.0 (free but it's the same version as premium so I'm assuming they are the same) and the class is in it. Try to redownload MythicMobs and try again.

**Comment by Crazall** [comment]
Thanks, I update MythicMobs to 5.2.1, it works!
