### ISSUE TITLE
Can't finish quest creation.

### ISSUE THREAD

**Issue by legendcuzican13** [SkytAsul/BeautyQuests#252]
**Describe the bug**	
I really love this plugin. It helps me make my server more unique and stand out some more. However it has this bug where I cannot complete the quest creation process. The gold ingot which usually finishes quest creation on press becomes draggable as shown here:
![image](https://user-images.githubusercontent.com/108838775/207758693-34c39594-ba39-494b-b7bd-85f708ea1916.png)

**Reproduction**
I simply made a quest that requires the player to bring back some items, break 25 blocks, and kill 25 magma slimes. The quest is then supposed to reward the player which gold leggings with a custom enchant.

**Screenshots, error messages**
Are there error messages in the console or in the chat?

**Software**
BeautyQuests version:
Game version: 0.19.7
Server version: 1.8
Server type (e.i. PaperSpigot): FlamePaper, was also having the same issue with BurritoSpigot and normal PaperMC
Are you using a protocol hack (like ViaVersion)?

If this can be fixed, please contact me at Legxnd#4194 on discord or just get back to me on GitHub, thanks!

**Comment by legendcuzican13** [comment]
I also want to note, this server is running protocol support and is cracked MC which can be played in the browser(its called eaglercraft). However, I don't think that this could be related to the bug as eaglercraft works just like any other real MC 1.8 or 1.5.2 server.

**Comment by SkytAsul** [comment]
> Are there error messages in the console or in the chat?
You haven't answered this question in the issue template. There must be an error in console when you click on the gold button.

**Comment by legendcuzican13** [comment]
ok I've found an error

**Comment by legendcuzican13** [comment]
Could not pass event InventoryClickEvent to BeautyQuests v0.19.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:741) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:680) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:583) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.potion.PotionData org.bukkit.inventory.meta.PotionMeta.getBasePotionData()'
	at fr.skytasul.quests.utils.MinecraftNames.getMaterialName(MinecraftNames.java:87) ~[?:?]
	at fr.skytasul.quests.gui.ItemUtils.getName(ItemUtils.java:288) ~[?:?]
	at fr.skytasul.quests.utils.Utils.getStringFromItemStack(Utils.java:137) ~[?:?]
	at fr.skytasul.quests.stages.StageBringBack.<init>(StageBringBack.java:51) ~[?:?]
	at fr.skytasul.quests.stages.StageBringBack$Creator.createStage(StageBringBack.java:230) ~[?:?]
	at fr.skytasul.quests.stages.StageBringBack$Creator.createStage(StageBringBack.java:1) ~[?:?]
	at fr.skytasul.quests.stages.StageNPC$AbstractCreator.finishStage(StageNPC.java:354) ~[?:?]
	at fr.skytasul.quests.stages.StageNPC$AbstractCreator.finishStage(StageNPC.java:1) ~[?:?]
	at fr.skytasul.quests.api.stages.StageCreation.finish(StageCreation.java:155) ~[?:?]
	at fr.skytasul.quests.gui.creation.FinishGUI.loadBranch(FinishGUI.java:256) ~[?:?]
	at fr.skytasul.quests.gui.creation.FinishGUI.finish(FinishGUI.java:203) ~[?:?]
	at fr.skytasul.quests.gui.creation.FinishGUI.access$2(FinishGUI.java:170) ~[?:?]
	at fr.skytasul.quests.gui.creation.FinishGUI$3.click(FinishGUI.java:138) ~[?:?]
	at fr.skytasul.quests.gui.creation.FinishGUI.onClick(FinishGUI.java:161) ~[?:?]
	at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:78) ~[?:?]
	at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:129) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor298.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[FlamePaper.jar:git-PaperSpigot-"d3366b1"]
	... 16 more

**Comment by SkytAsul** [comment]
Fixed in https://github.com/SkytAsul/BeautyQuests/commit/93003c01c19b6b91bcadf43925512e392d5e5145. Use [dev build 348](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/).
