### ISSUE TITLE
The task does not run normally after adding the "addsound" option to the NPC dialog

### ISSUE THREAD

**Issue by Ghost067** [SkytAsul/BeautyQuests#253]
After I use the "addsound" option in my conversation for NPC, the task has an error and the console has reported an error.
At the same time, I want to ask whether there is an example of the "addsound" option for reference.
My English level is not very high, please let me know if the description is not clear.
The following error messages are output from the console.

[21:14:33] [Server thread/ERROR]: Could not pass event BQNPCClickEvent to BeautyQuests v0.20
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at fr.skytasul.quests.api.npcs.BQNPCsManager.clickEvent(BQNPCsManager.java:59) ~[?:?]
        at fr.skytasul.quests.utils.compatibility.npcs.BQCitizens.onNPCRightClick(BQCitizens.java:54) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor250.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:523) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2104) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:74) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: net.minecraft.server.v1_16_R3.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:ENTITY_VILLAGER_AMBIENT
        at net.minecraft.server.v1_16_R3.MinecraftKey.<init>(SourceFile:41) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftKey.<init>(SourceFile:46) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:512) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:500) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at fr.skytasul.quests.utils.types.Message.finished(Message.java:100) ~[?:?]
        at fr.skytasul.quests.utils.types.DialogRunner.send(DialogRunner.java:160) ~[?:?]
        at fr.skytasul.quests.utils.types.DialogRunner.handleNext(DialogRunner.java:117) ~[?:?]
        at fr.skytasul.quests.utils.types.DialogRunner.onClick(DialogRunner.java:97) ~[?:?]
        at fr.skytasul.quests.stages.StageNPC.onClick(StageNPC.java:185) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor251.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        ... 35 more

**Comment by SkytAsul** [comment]
Use `entity.villager.ambient` instead of `ENTITY_VILLAGER_AMBIENT`.

**Comment by Ghost067** [comment]
Thanks, at the same time I have a new issue, the console outputs an error when selecting the "MythicMobs" option, and this option does not work properly.
The following error messages are output from the console.

[13:15:25] [Server thread/ERROR]: [BeautyQuests] Cannot open inventory  to player Cronus_
java.lang.NoSuchMethodError: 'io.lumine.mythic.api.mobs.entities.MythicEntityType io.lumine.mythic.api.mobs.MythicMob.getEntityType()'
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5.getEntityType(MythicMobs5.java:97) ~[?:?]
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5$1.getItemStack(MythicMobs5.java:49) ~[?:?]
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5$1.getItemStack(MythicMobs5.java:44) ~[?:?]
        at fr.skytasul.quests.gui.templates.PagedGUI.setItems(PagedGUI.java:114) ~[?:?]
        at fr.skytasul.quests.gui.templates.PagedGUI.open(PagedGUI.java:73) ~[?:?]
        at fr.skytasul.quests.gui.Inventories.create(Inventories.java:46) ~[?:?]
        at fr.skytasul.quests.gui.CustomInventory.create(CustomInventory.java:53) ~[?:?]
        at fr.skytasul.quests.utils.compatibility.mobs.MythicMobs5.itemClick(MythicMobs5.java:62) ~[?:?]
        at fr.skytasul.quests.gui.mobs.MobSelectionGUI.click(MobSelectionGUI.java:33) ~[?:?]
        at fr.skytasul.quests.gui.mobs.MobSelectionGUI.click(MobSelectionGUI.java:17) ~[?:?]
        at fr.skytasul.quests.gui.templates.PagedGUI.onClick(PagedGUI.java:183) ~[?:?]
        at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:84) ~[?:?]
        at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:132) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2436) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:16:38] [lumine-scheduler-16/ERROR]: [MythicMobs] Couldn't save json in module: io.lumine.mythic.core.mobs.MobExecutor
[13:16:38] [Server thread/ERROR]: [MythicMobs] Couldn't save json in module: io.lumine.mythic.core.skills.variables.VariableManager
[13:16:38] [lumine-scheduler-16/WARN]: java.io.FileNotFoundException: plugins\MythicMobs\SavedData\active-mobs.json (系统找不到指定的路径。)
[13:16:38] [lumine-scheduler-16/WARN]:  at java.base/java.io.FileOutputStream.open0(Native Method)
[13:16:38] [lumine-scheduler-16/WARN]:  at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
[13:16:38] [lumine-scheduler-16/WARN]:  at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
[13:16:38] [lumine-scheduler-16/WARN]:  at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[13:16:38] [lumine-scheduler-16/WARN]:  at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
[13:16:38] [lumine-scheduler-16/WARN]:  at io.lumine.mythic.utils.serialization.SerializingModule.saveJson(SerializingModule.java:138)
[13:16:38] [lumine-scheduler-16/WARN]:  at io.lumine.mythic.utils.serialization.WrappedJsonFile.save(WrappedJsonFile.java:29)
[13:16:38] [lumine-scheduler-16/WARN]:  at io.lumine.mythic.core.mobs.MobExecutor.lambda$saveCachedActiveMobs$5(MobExecutor.java:685)
[13:16:38] [lumine-scheduler-16/WARN]:  at io.lumine.mythic.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
[13:16:38] [lumine-scheduler-16/WARN]:  at io.lumine.mythic.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
[13:16:38] [lumine-scheduler-16/WARN]:  at io.lumine.mythic.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[13:16:38] [lumine-scheduler-16/WARN]:  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[13:16:38] [lumine-scheduler-16/WARN]:  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[13:16:38] [lumine-scheduler-16/WARN]:  at java.base/java.lang.Thread.run(Thread.java:831)
[13:16:38] [Server thread/WARN]: java.io.FileNotFoundException: plugins\MythicMobs\SavedData\global-data.json (系统找不到指定的路径。)
[13:16:38] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[13:16:38] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
[13:16:38] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
[13:16:38] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[13:16:38] [Server thread/WARN]:        at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
[13:16:38] [Server thread/WARN]:        at io.lumine.mythic.utils.serialization.SerializingModule.saveJson(SerializingModule.java:138)
[13:16:38] [Server thread/WARN]:        at io.lumine.mythic.utils.serialization.WrappedJsonFile.save(WrappedJsonFile.java:29)
[13:16:38] [Server thread/WARN]:        at io.lumine.mythic.core.skills.variables.VariableManager.save(VariableManager.java:53)
[13:16:38] [Server thread/WARN]:        at io.lumine.mythic.core.config.ConfigManager.save(ConfigManager.java:153)
[13:16:38] [Server thread/WARN]:        at io.lumine.mythic.bukkit.clock.MythicClock.executeSave(MythicClock.java:115)
[13:16:38] [Server thread/WARN]:        at io.lumine.mythic.bukkit.clock.MythicClock.runSavingClock(MythicClock.java:77)
[13:16:38] [Server thread/WARN]:        at io.lumine.mythic.utils.Delegates$RunnableToConsumer.accept(Delegates.java:93)
[13:16:38] [Server thread/WARN]:        at io.lumine.mythic.utils.Schedulers$LumineTask.run(Schedulers.java:162)
[13:16:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[13:16:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[13:16:38] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1179)
[13:16:38] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394)
[13:16:38] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127)
[13:16:38] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966)
[13:16:38] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[13:16:38] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by SkytAsul** [comment]
You're running an outdated MythicMobs version. Update to 5.2.0.
