### ISSUE TITLE
BeautyQuests ne semble pas être compatible avec les mods

### ISSUE THREAD

**Issue by 615303619** [SkytAsul/BeautyQuests#255]
**Describe the bug**	
A clear and concise description of what the bug is and how it occurs.
BeautyQuests ne semble pas être compatible avec les mods, non? Lorsque j’essaie de définir l’élément de mod sur 'ramener l’élément', l’arrière-plan commence à signaler une erreur lorsque la tâche est enregistrée, et la mauvaise partie n’est pas enregistrée
**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)
idem
**Screenshots, error messages**
Are there error messages in the console or in the chat?
`[18:47:41] [信息]: [BeautyQuests] Total loaded accounts: 7
[18:47:41] [错误]: [BeautyQuests] An error occurred wheh creating branch from GUI.
java.lang.IllegalArgumentException: Unsupported material from item: ICEANDFIRE_SILVER_INGOT (0)
	at fr.skytasul.quests.utils.XMaterial.matchXMaterial(XMaterial.java:1772) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.utils.MinecraftNames.getMaterialName(MinecraftNames.java:86) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.gui.ItemUtils.getName(ItemUtils.java:288) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.utils.Utils.getStringFromItemStack(Utils.java:148) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.stages.StageBringBack.<init>(StageBringBack.java:49) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.stages.StageBringBack$Creator.createStage(StageBringBack.java:235) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.stages.StageBringBack$Creator.createStage(StageBringBack.java:227) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.stages.StageNPC$AbstractCreator.finishStage(StageNPC.java:352) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.stages.StageNPC$AbstractCreator.finishStage(StageNPC.java:285) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.api.stages.StageCreation.finish(StageCreation.java:175) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.gui.creation.FinishGUI.loadBranch(FinishGUI.java:257) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.gui.creation.FinishGUI.finish(FinishGUI.java:204) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.gui.creation.FinishGUI.access$200(FinishGUI.java:41) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.gui.creation.FinishGUI$3.click(FinishGUI.java:139) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.gui.creation.FinishGUI.onClick(FinishGUI.java:162) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:84) ~[任务-beautyquests-0.20.0.jar:?]
	at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:132) ~[任务-beautyquests-0.20.0.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor302.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:578) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:2278) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:886) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:869) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:863) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:849) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:781) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[18:47:42] [信息]: [BeautyQuests] New quest created: --初到神之愿--, ID 0, by Zoe__May
[18:47:42] [信息]: [BeautyQuests] Quest --初到神之愿-- has been edited
[18:47:42] [信息]: [BeautyQuests] Creating single quest backup...`
**Software**
BeautyQuests version:0.20
Game version:1.16.5 
Server version:1.16.5
Server type (e.i. PaperSpigot):catserver
Are you using a protocol hack (like ViaVersion)?
no
**Additional context (optional)**
J’ai utilisé le traducteur, s’il y a une partie que vous ne pouvez pas comprendre, s’il vous plaît demandez-moi
(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
BeautyQuests is indeed not compatible with mods for "bring items to NPC" or "mine/place blocks" stages, sorry!
