### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by hubhubhubzen** [SkytAsul/BeautyQuests#266]
**Describe the bug**	
Console spam. IDK where is the error but It would be cool to fix it

**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

**Screenshots, error messages**
[15:28:49 WARN]: [BeautyQuests] Task #385 for BeautyQuests v0.20.1 generated an exception
java.lang.NoSuchMethodError: 'void eu.decentsoftware.holograms.api.holograms.Hologram.removeShowPlayer(org.bukkit.entity.Player)'
at fr.skytasul.quests.utils.compatibility.BQDecentHolograms$DecentHologram.setPlayerVisibility(BQDecentHolograms.java:60) ~[beautyquests-0.20.1.jar:?]
at fr.skytasul.quests.api.npcs.BQNPC$Hologram.setVisible(BQNPC.java:393) ~[beautyquests-0.20.1.jar:?]
at fr.skytasul.quests.api.npcs.BQNPC$2.run(BQNPC.java:131) ~[beautyquests-0.20.1.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-379]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-379]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-379]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-379]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-379]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-379]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
at java.lang.Thread.run(Unknown Source) ~[?:?]
It's spamming every 4 sec in console

**Software**
BeautyQuests version: newest 20.1
Game version: 1.18.2
Server version: 1.18.2
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? No)

**Comment by EnderGriefeur99** [comment]
update your DecentHologram version.
