### ISSUE TITLE
Error at creating quest

### ISSUE THREAD

**Issue by MrRoddd** [SkytAsul/BeautyQuests#268]
I'll resend my last issue cause maybe you didn't see it, and if you did, I'm sorry.
Describe the bug
Error code: This option is already attached to 0 in FishingGUI

Reproduction
When I click in the gold block to create the quest.

Screenshots, error messages
Are there error messages in the console or in the chat?
https://user-images.githubusercontent.com/129146501/230139605-e9a8088d-6c24-4768-86a6-2c79ebcb2060.png

Software
BeautyQuests version: 0.20.1
Game version: 1.19.3
Server version: 1.19.3
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? I tested it on my test server so I don't have it, but in my main server I have viaversions

Additional context (optional)
[Server thread/ERROR]: [BeautyQuests] An error occurred when MrRodd clicked in inventory FinishGUI at slot 5
java.lang.IllegalStateException: This option is already attached to 0
at fr.skytasul.quests.api.options.QuestOption.attach(QuestOption.java:78) ~[?:?]
at fr.skytasul.quests.structure.Quest.addOption(Quest.java:117) ~[?:?]
at fr.skytasul.quests.gui.creation.FinishGUI.finish(FinishGUI.java:193) ~[?:?]
at fr.skytasul.quests.gui.creation.FinishGUI.access$200(FinishGUI.java:39) ~[?:?]
at fr.skytasul.quests.gui.creation.FinishGUI$3.click(FinishGUI.java:137) ~[?:?]
at fr.skytasul.quests.gui.creation.FinishGUI.onClick(FinishGUI.java:160) ~[?:?]
at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:84) ~[?:?]
at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:132) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2763) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1133) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1110) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

Here is a video!
https://www.youtube.com/watch?v=Y_xFVWQtbe0&ab_channel=MinePixelSurvival

**Comment by SkytAsul** [comment]
No need to create two issues
