### ISSUE TITLE
Update to 0.13 broke one of my quests

### ISSUE THREAD

**Issue by marvinej** [SkytAsul/BeautyQuests#27]
[01:00:48] [Server thread/ERROR]: [BeautyQuests] Error when deserializing the stage 3 for the quest Bank Robbery
[01:00:48] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[01:00:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:00:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:00:48] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:00:48] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.api.stages.AbstractStage.deserialize(AbstractStage.java:203)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.stages.StageManager.deserialize(StageManager.java:254)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.deserialize(Quest.java:576)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.loadFromFile(Quest.java:556)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.BeautyQuests.loadAllDatas(BeautyQuests.java:290)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.BeautyQuests$1.run(BeautyQuests.java:115)
[01:00:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[01:00:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[01:00:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:00:48] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Text cannot be null
[01:00:48] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.stages.StageChat.<init>(StageChat.java:26)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.stages.StageChat.deserialize(StageChat.java:72)
[01:00:48] [Server thread/WARN]: 	... 17 more
[01:00:48] [Server thread/WARN]: [BeautyQuests] Error when loading quests from data file.
[01:00:48] [Server thread/WARN]: java.lang.NullPointerException
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.unloadAll(Quest.java:489)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.deserialize(Quest.java:578)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.loadFromFile(Quest.java:556)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.BeautyQuests.loadAllDatas(BeautyQuests.java:290)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.BeautyQuests$1.run(BeautyQuests.java:115)
[01:00:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[01:00:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[01:00:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:00:48] [Server thread/ERROR]: [BeautyQuests] Quest from file 5.yml not activated
[01:00:48] [Server thread/ERROR]: [BeautyQuests] Error when deserializing the stage 1 for the quest Welcome
[01:00:48] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[01:00:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:00:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:00:48] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:00:48] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.api.stages.AbstractStage.deserialize(AbstractStage.java:203)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.stages.StageManager.deserialize(StageManager.java:254)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.deserialize(Quest.java:576)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.loadFromFile(Quest.java:556)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.BeautyQuests.loadAllDatas(BeautyQuests.java:290)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.BeautyQuests$1.run(BeautyQuests.java:115)
[01:00:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[01:00:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[01:00:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:00:48] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Text cannot be null
[01:00:48] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.stages.StageChat.<init>(StageChat.java:26)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.stages.StageChat.deserialize(StageChat.java:72)
[01:00:48] [Server thread/WARN]: 	... 17 more
[01:00:48] [Server thread/WARN]: [BeautyQuests] Error when loading quests from data file.
[01:00:48] [Server thread/WARN]: java.lang.NullPointerException
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.unloadAll(Quest.java:489)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.deserialize(Quest.java:578)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.Quest.loadFromFile(Quest.java:556)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.BeautyQuests.loadAllDatas(BeautyQuests.java:290)
[01:00:48] [Server thread/WARN]: 	at fr.skytasul.quests.BeautyQuests$1.run(BeautyQuests.java:115)
[01:00:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[01:00:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[01:00:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[01:00:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:00:48] [Server thread/ERROR]: [BeautyQuests] Quest from file 1.yml not activated
[01:00:48] [Server thread/INFO]: [BeautyQuests] Periodic saves task started (18000 ticks). Task ID: 1566
[01:00:48] [Server thread/INFO]: [BeautyQuests] 4 quests loaded (0.044s)!

**Comment by SkytAsul** [comment]
There is a problem with you quest data : in the stage with chat message, "writeText" has not been saved.

**Comment by SkytAsul** [comment]
If you still have this issue, please contact me via Discord.
