### ISSUE TITLE
Issue getting NPC

### ISSUE THREAD

**Issue by Morgs626** [SkytAsul/BeautyQuests#271]
I am having an issue spawning a NPC to start a quest. I did download Citizens via the link from you spigot page. When I try I get the message in the picture but I can't find anything that says I should change anything to make the 2 compatible, if that even is the problem. I have tried this both on Spigot and paper servers and get the same on both. Do I need citizen's 2 for it maybe?
![1](https://user-images.githubusercontent.com/131304971/233191258-2168d200-ce4e-45dd-ac00-f6db8d74aa2b.png)

**Comment by SkytAsul** [comment]
Read your logs. Everything must be told in there.

**Comment by Morgs626** [comment]
20.04 22:50:43 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'npc' in plugin Citizens v2.0.13-SNAPSHOT (build 1130) - plugin is disabled.
20.04 22:50:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
20.04 22:50:43 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
20.04 22:50:43 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-514]
20.04 22:50:43 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-514]
20.04 22:50:43 [Server] INFO at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
20.04 22:50:43 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
20.04 22:50:43 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
20.04 22:50:43 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2290) ~[?:?]
20.04 22:50:43 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2250) ~[?:?]
20.04 22:50:43 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
20.04 22:50:43 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
20.04 22:50:43 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-514]
20.04 22:50:43 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
20.04 22:50:43 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
20.04 22:50:43 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-514]
20.04 22:50:43 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-514]
20.04 22:50:43 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
20.04 22:50:43 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-514]
20.04 22:50:43 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-514]
20.04 22:50:43 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
20.04 22:50:43 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-514]
20.04 22:50:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-514]
20.04 22:50:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-514]


So my plugin is disabled? How do I enable it?

**Comment by SkytAsul** [comment]
Your version of Citizens is 9 years old. Download a more recent one here: https://ci.citizensnpcs.co/job/Citizens2/
