### ISSUE TITLE
BeautyQuest Bug

### ISSUE THREAD

**Issue by Cheminsky953** [SkytAsul/BeautyQuests#278]
[13:11:39 ERROR]: [BeautyQuests] An error occurred while updating quests handler.
java.lang.NullPointerException: null
        at fr.skytasul.quests.scoreboards.ScoreboardManager.questEvent(ScoreboardManager.java:219) ~[?:?]
        at fr.skytasul.quests.scoreboards.ScoreboardManager.questUpdated(ScoreboardManager.java:207) ~[?:?]
        at fr.skytasul.quests.structure.BranchesManager.lambda$objectiveUpdated$0(BranchesManager.java:73) ~[?:?]
        at fr.skytasul.quests.api.QuestsAPI.lambda$propagateQuestsHandlers$1(QuestsAPI.java:177) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at fr.skytasul.quests.api.QuestsAPI.propagateQuestsHandlers(QuestsAPI.java:175) ~[?:?]
        at fr.skytasul.quests.structure.BranchesManager.objectiveUpdated(BranchesManager.java:73) ~[?:?]
        at fr.skytasul.quests.api.stages.AbstractStage.updateObjective(AbstractStage.java:259) ~[?:?]
        at fr.skytasul.quests.api.stages.types.AbstractCountableStage.updatePlayerRemaining(AbstractCountableStage.java:113) ~[?:?]
        at fr.skytasul.quests.api.stages.types.AbstractCountableStage.event(AbstractCountableStage.java:194) ~[?:?]
        at fr.skytasul.quests.stages.StageMine.onMine(StageMine.java:75) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor283.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[mohist-1.16.5-1124-universal.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[mohist-1.16.5-1124-universal.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[mohist-1.16.5-1124-universal.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[mohist-1.16.5-1124-universal.jar:?]
        at fr.skytasul.quests.QuestsListener.onBreak(QuestsListener.java:219) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor383.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[mohist-1.16.5-1124-universal.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[mohist-1.16.5-1124-universal.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[mohist-1.16.5-1124-universal.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[mohist-1.16.5-1124-universal.jar:?]
        at com.mohistmc.eventhandler.dispatcher.BlockEventDispatcher.onBreakBlockEvent(BlockEventDispatcher.java:55) ~[mohist-1.16.5-1124-universal.jar:?]
        at net.minecraftforge.eventbus.ASMEventHandler_110_BlockEventDispatcher_onBreakBlockEvent_BreakEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[custom.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:284) ~[custom.jar:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:604) ~[forge:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:298) ~[?:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:287) ~[?:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:257) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:1364) ~[?:?]
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:938) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:175) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:921) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:915) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:901) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:268) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]

**Comment by SkytAsul** [comment]
Mohist is not supported software, bugs are expected and will not be fixed. It is likely that complex systems such as Scoreboards will fail. You should disable them completely in BeautyQuests' config.yml:
https://github.com/SkytAsul/BeautyQuests/blob/aa44729b9826155c8aa1ac7bddca4a268bf7bbfc/core/src/main/resources/config.yml#L37
