### ISSUE TITLE
could not pass event

### ISSUE THREAD

**Issue by scalap02** [SkytAsul/BeautyQuests#291]
Bonjour j'ai un problème, sur mon sevreur mohist en 1.16.5, sur la version 0.20.1, un message d'erreur apparaît très fréquemment et il me semble que cela me pompe de la rame, je sais que les quêtes n'acceptent pas les objets moddés, je n'en ai pas mis mais j'ai quand même ce message : 
------------------------------------------------------------------------------------------------------------------------------------------------------
[17:29:13 ERROR]: Could not pass event BQBlockBreakEvent to BeautyQuests v0.20.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[mohist-1.16.5-1161-universal.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[mohist-1.16.5-1161-universal.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[mohist-1.16.5-1161-universal.jar:?]
        at fr.skytasul.quests.QuestsListener.onBreak(QuestsListener.java:219) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor151.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[mohist-1.16.5-1161-universal.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[mohist-1.16.5-1161-universal.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[mohist-1.16.5-1161-universal.jar:?]
        at com.mohistmc.eventhandler.dispatcher.BlockEventDispatcher.onBreakBlockEvent(BlockEventDispatcher.java:55) ~[mohist-1.16.5-1161-universal.jar:?]
        at net.minecraftforge.eventbus.ASMEventHandler_62_BlockEventDispatcher_onBreakBlockEvent_BreakEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:284) ~[server.jar:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:604) ~[forge:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:299) ~[?:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:288) ~[?:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:236) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:1363) ~[?:?]
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:936) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:174) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:919) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:913) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:990) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:815) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Unsupported material with no data value: BIOMESOPLENTY_BUSH
        at fr.skytasul.quests.utils.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1722) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at fr.skytasul.quests.utils.XMaterial.matchXMaterial(XMaterial.java:1722) ~[?:?]
        at fr.skytasul.quests.utils.XBlock.isSimilar(XBlock.java:605) ~[?:?]
        at fr.skytasul.quests.utils.types.BQBlock$BQBlockMaterial.applies(BQBlock.java:158) ~[?:?]
        at fr.skytasul.quests.api.stages.types.AbstractCountableBlockStage.objectApplies(AbstractCountableBlockStage.java:27) ~[?:?]
        at fr.skytasul.quests.api.stages.types.AbstractCountableBlockStage.objectApplies(AbstractCountableBlockStage.java:19) ~[?:?]
        at fr.skytasul.quests.api.stages.types.AbstractCountableStage.event(AbstractCountableStage.java:170) ~[?:?]
        at fr.skytasul.quests.stages.StageMine.onMine(StageMine.java:75) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor134.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[mohist-1.16.5-1161-universal.jar:?]
        ... 35 more

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by EnderGriefeur99** [comment]
Mohist n'est pas et ne sera jamais supporté. Tout serveur mixant l'api bukkit et forge est foireux et occasionnera ce genre de bugs.
Dans ton cas, les types de blocs custom clashent avec le système de rétro-compatibilité.
