### ISSUE TITLE
Erreur Dynmap au démarrage

### ISSUE THREAD

**Issue by KeyKatyu** [SkytAsul/BeautyQuests#298]
**Describe the bug**	
Une erreur apparaît au démarrage du serveur. En lien avec DynMap.

**Screenshots, error messages**
```
[10:17:17 ERROR]: [BeautyQuests] Cannot load quest handler fr.skytasul.quests.integrations.maps.BQDynmap
java.lang.IllegalStateException: BeautyQuests is not yet initialized
        at fr.skytasul.quests.BeautyQuests.ensureLoaded(BeautyQuests.java:742) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at fr.skytasul.quests.BeautyQuests.getQuestsManager(BeautyQuests.java:778) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at fr.skytasul.quests.QuestsAPIImplementation.getQuestsManager(QuestsAPIImplementation.java:210) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at fr.skytasul.quests.api.AbstractMapIntegration.initializeQuests(AbstractMapIntegration.java:17) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at fr.skytasul.quests.integrations.maps.BQDynmap.initializeMarkers(BQDynmap.java:44) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at fr.skytasul.quests.api.AbstractMapIntegration.load(AbstractMapIntegration.java:13) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at fr.skytasul.quests.BeautyQuests.lambda$loadAllDatas$9(BeautyQuests.java:500) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at fr.skytasul.quests.BeautyQuests.loadAllDatas(BeautyQuests.java:498) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at fr.skytasul.quests.BeautyQuests.access$000(BeautyQuests.java:65) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at fr.skytasul.quests.BeautyQuests$1.run(BeautyQuests.java:173) ~[beautyquests-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-297]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-297]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Software**
BeautyQuests version: 1.0_BUILD386
Game version: 1.20.2
Server version: Paper
Server type (e.i. PaperSpigot): Paper 1.20.2
Are you using a protocol hack (like ViaVersion)? Non

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
C'est fix ! Je peux t'envoyer un JAR en DM sur Discord pour que tu testes ? Je ne peux pas faire tourner dynmap sur ma machine perso pour essayer...

**Comment by KeyKatyu** [comment]
Yes pas de souci, mon Discord : keykatyu
