### ISSUE TITLE
[16:00:57 ERROR]: Could not pass event PlayerItemConsumeEvent to BeautyQuests v1.0.2

### ISSUE THREAD

**Issue by taoyoukai** [SkytAsul/BeautyQuests#309]
**Describe the bug**	
A clear and concise description of what the bug is and how it occurs.

**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

**Screenshots, error messages**
Are there error messages in the console or in the chat?
[16:00:57 ERROR]: Could not pass event PlayerItemConsumeEvent to BeautyQuests v1.0.2
java.lang.IllegalStateException: Trying to fetch data of not launched stage
        at fr.skytasul.quests.structure.StageControllerImplementation.getData(StageControllerImplementation.java:106) ~[beautyquests-1.0.2.jar:?]
        at fr.skytasul.quests.api.stages.AbstractStage.getData(AbstractStage.java:180) ~[beautyquests-1.0.2.jar:?]
        at fr.skytasul.quests.api.stages.types.AbstractCountableStage.getPlayerRemainings(AbstractCountableStage.java:57) ~[beautyquests-1.0.2.jar:?]
        at fr.skytasul.quests.api.stages.types.AbstractCountableStage.event(AbstractCountableStage.java:163) ~[beautyquests-1.0.2.jar:?]
        at fr.skytasul.quests.stages.StageEatDrink.onItemConsume(StageEatDrink.java:37) ~[beautyquests-1.0.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1289.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2127]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:4136) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:1959) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3996) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2649) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3976) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3095) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:301) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:789) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:353) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:601) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:240) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1769) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1546) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
**Software**
BeautyQuests version:
Game version:1.20.4
Server version:1.20.4
Server type (e.i. PaperSpigot): purpur(paper)
Are you using a protocol hack (like ViaVersion)?
yes viaversion via rewind
**Additional context (optional)**
they are using 1.20.4 but still bugs

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Yup that's my bad, I'm fixing it!

**Comment by SkytAsul** [comment]
Try the latest dev build: https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/
