### ISSUE TITLE
LevelledMobs error

### ISSUE THREAD

**Issue by taoyoukai** [SkytAsul/BeautyQuests#311]
**Describe the bug**	
A clear and concise description of what the bug is and how it occurs.

**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

**Screenshots, error messages**
Are there error messages in the console or in the chat?
[22:27:16 ERROR]: Could not pass event BQMobDeathEvent to BeautyQuests v1.0.3_BUILD394
java.lang.IllegalStateException: Cannot get plugin for class me.lokka30.levelledmobs.LevelledMobs from a static initializer
        at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:429) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at fr.skytasul.quests.integrations.mobs.BQLevelledMobs.getMobLevel(BQLevelledMobs.java:40) ~[beautyquests-1.0.3-SNAPSHOT.jar:?]
        at fr.skytasul.quests.integrations.mobs.BQLevelledMobs.getMobLevel(BQLevelledMobs.java:18) ~[beautyquests-1.0.3-SNAPSHOT.jar:?]
        at fr.skytasul.quests.mobs.Mob.getLevel(Mob.java:97) ~[beautyquests-1.0.3-SNAPSHOT.jar:?]
        at fr.skytasul.quests.stages.StageMobs.objectApplies(StageMobs.java:71) ~[beautyquests-1.0.3-SNAPSHOT.jar:?]
        at fr.skytasul.quests.stages.StageMobs.objectApplies(StageMobs.java:35) ~[beautyquests-1.0.3-SNAPSHOT.jar:?]
        at fr.skytasul.quests.api.stages.types.AbstractCountableStage.event(AbstractCountableStage.java:163) ~[beautyquests-1.0.3-SNAPSHOT.jar:?]
        at fr.skytasul.quests.stages.StageMobs.onMobKilled(StageMobs.java:60) ~[beautyquests-1.0.3-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1476.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2127]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at fr.skytasul.quests.api.mobs.MobFactory.callEvent(MobFactory.java:113) ~[beautyquests-1.0.3-SNAPSHOT.jar:?]
        at fr.skytasul.quests.mobs.BukkitEntityFactory.onEntityKilled(BukkitEntityFactory.java:75) ~[beautyquests-1.0.3-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1062.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2127]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:968) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1899) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1791) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1604) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:356) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:411) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:241) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:232) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:304) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:240) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:113) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1497) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:945) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:922) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1747) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1546) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[22:27:16 INFO]: [MobMoney] [MOBMONEY DEBUG] Entity killed: ZOMBIE
[22:27:16 INFO]: [MobMoney] [MOBMONEY DEBUG] New strike: 3
**Software**
BeautyQuests version:
Game version:1.20.4
Server version:1.20.4
Server type (e.i. PaperSpigot):purpur
Are you using a protocol hack (like ViaVersion)?
is both viaversion/backwards
**Additional context (optional)**
all players using 1.20.4 still have this error

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Sorry I haven't seen this issue until now. Did it happen after an update of LevelledMobs?
