### ISSUE TITLE
The quest editor cannot be edited MythicMobs.

### ISSUE THREAD

**Issue by Ghost067** [SkytAsul/BeautyQuests#320]
**Describe the bug**	
After opening the quest editor for any quests, adding a new stage to kill MythicMobs or editing will cause an issue.

**Reproduction**
The description above is clear.

**Screenshots, error messages**
[00:16:28 ERROR]: Could not pass event InventoryClickEvent to BeautyQuests v1.0.3
java.lang.NoSuchMethodError: 'io.lumine.mythic.api.mobs.entities.MythicEntityType io.lumine.mythic.api.mobs.MythicMob.getEntityType()'
        at fr.skytasul.quests.integrations.mobs.MythicMobs5.getEntityType(MythicMobs5.java:97) ~[?:?]
        at fr.skytasul.quests.integrations.mobs.MythicMobs5.getEntityType(MythicMobs5.java:29) ~[?:?]
        at fr.skytasul.quests.mobs.Mob.getMobItem(Mob.java:78) ~[?:?]
        at fr.skytasul.quests.gui.mobs.MobsListGUI.getObjectItemStack(MobsListGUI.java:86) ~[?:?]
        at fr.skytasul.quests.gui.mobs.MobsListGUI.getObjectItemStack(MobsListGUI.java:23) ~[?:?]
        at fr.skytasul.quests.api.gui.templates.ListGUI.getItemStack(ListGUI.java:43) ~[?:?]
        at fr.skytasul.quests.api.gui.templates.PagedGUI.setItems(PagedGUI.java:146) ~[?:?]
        at fr.skytasul.quests.api.gui.templates.PagedGUI.populate(PagedGUI.java:85) ~[?:?]
        at fr.skytasul.quests.api.gui.AbstractGui.showInternal(AbstractGui.java:23) ~[?:?]
        at fr.skytasul.quests.gui.GuiManagerImplementation.open(GuiManagerImplementation.java:43) ~[?:?]
        at fr.skytasul.quests.api.gui.Gui.open(Gui.java:36) ~[?:?]
        at fr.skytasul.quests.stages.StageMobs$Creator.lambda$setupLine$1(StageMobs.java:171) ~[?:?]
        at fr.skytasul.quests.gui.creation.stages.StagesGUI.onClick(StagesGUI.java:161) ~[?:?]
        at fr.skytasul.quests.gui.GuiManagerImplementation.onClick(GuiManagerImplementation.java:183) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor806.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Software**
BeautyQuests version: 1.0.3
Game version: 1.16.5
Server version: 1.16.5
Server type (e.i. PaperSpigot): PaperSpigot
Are you using a protocol hack (like ViaVersion)? No

**Additional context (optional)**
None

**Comment by EnderGriefeur99** [comment]
Mm version ?

**Comment by Ghost067** [comment]
MM version is 5.1.4.

**Comment by SkytAsul** [comment]
Please update to a more recent version of MythicMobs and tell us if it still does not work.

**Comment by Ghost067** [comment]
Well, there is no problem with upgrading the MM version to 5.2 or above. But my server is 1.16.5, and the server uses MythicMobsExtension, which can only support version 5.1 MM on 1.16.5, can it be adapted to the following versions? Thank you very much.
