### ISSUE TITLE
scoreboard displays incorrectly

### ISSUE THREAD

**Issue by DuRouRou** [SkytAsul/BeautyQuests#321]
Describe the bug
The in-game scoreboard displays incorrectly, and there are errors in the console.
﻿
Reproduction
I set up a quest and used the scoreboard for hints. After the quest was completed, the scoreboard froze on the display of the last progress and did not disappear.
At the same time as this happened, an error also occurred in the console.
﻿
Screenshots, error messages
﻿[00:31:02 WARN]: [BeautyQuests] Task #2777 for BeautyQuests v1.0.3 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.spawn(Lorg/bukkit/Location;Ljava/lang/Class;Ljava/util/function/Consumer;)Lorg/bukkit/entity/Entity;
        at fr.skytasul.quests.utils.QuestUtils.lambda$spawnFirework$4(QuestUtils.java:157) ~[?:?]
        at fr.skytasul.quests.utils.QuestUtils.runOrSync(QuestUtils.java:82) ~[?:?]
        at fr.skytasul.quests.utils.QuestUtils.spawnFirework(QuestUtils.java:151) ~[?:?]
        at fr.skytasul.quests.structure.QuestImplementation.lambda$finish$15(QuestImplementation.java:505) ~[?:?]
        at fr.skytasul.quests.utils.QuestUtils.runOrSync(QuestUtils.java:82) ~[?:?]
        at fr.skytasul.quests.structure.QuestImplementation.lambda$finish$16(QuestImplementation.java:493) ~[?:?]
        at fr.skytasul.quests.structure.QuestImplementation.finish(QuestImplementation.java:519) ~[?:?]
        at fr.skytasul.quests.structure.QuestBranchImplementation.lambda$finishPlayerStage$4(QuestBranchImplementation.java:211) ~[?:?]
        at fr.skytasul.quests.structure.QuestBranchImplementation.endStage(QuestBranchImplementation.java:267) ~[?:?]
        at fr.skytasul.quests.structure.QuestBranchImplementation.finishPlayerStage(QuestBranchImplementation.java:204) ~[?:?]
        at fr.skytasul.quests.structure.StageControllerImplementation.lambda$finishStage$0(StageControllerImplementation.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
﻿
Software
BeautyQuests version: 1.0.3
Game version: 1.12.2
Server version: 1.12.2
Server type (e.g., PaperSpigot): PaperSpigot-1.12.2
Are you using a protocol hack (like ViaVersion)? No
﻿
Additional context (optional)
Dear author, I did not encounter this error when using version 0.20.1, and I hope you can fix this error in the next version. Thank you very much! For now, I will revert to version 0.20.1 to continue making quests, waiting for your update before I use the new version again.

**Comment by SkytAsul** [comment]
It seems like a problem with fireworks. You can disable them in config.yml.
