### ISSUE TITLE
Sounds and fireworks cannot be played after the quest is completed.

### ISSUE THREAD

**Issue by Ghost067** [SkytAsul/BeautyQuests#325]
**Describe the bug**	
A clear and concise description of what the bug is and how it occurs.

As the title suggests.

**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

As the title suggests.

**Screenshots, error messages**
Are there error messages in the console or in the chat?

[16:07:52 WARN]: [BeautyQuests] Task #783792 for BeautyQuests v1.0.3 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.World.spawn(org.bukkit.Location, java.lang.Class, java.util.function.Consumer)'
        at fr.skytasul.quests.utils.QuestUtils.lambda$spawnFirework$4(QuestUtils.java:157) ~[?:?]
        at fr.skytasul.quests.utils.QuestUtils.runOrSync(QuestUtils.java:82) ~[?:?]
        at fr.skytasul.quests.utils.QuestUtils.spawnFirework(QuestUtils.java:151) ~[?:?]
        at fr.skytasul.quests.structure.QuestImplementation.lambda$finish$15(QuestImplementation.java:505) ~[?:?]
        at fr.skytasul.quests.utils.QuestUtils.runOrSync(QuestUtils.java:82) ~[?:?]
        at fr.skytasul.quests.structure.QuestImplementation.lambda$finish$16(QuestImplementation.java:493) ~[?:?]
        at fr.skytasul.quests.structure.QuestImplementation.finish(QuestImplementation.java:519) ~[?:?]
        at fr.skytasul.quests.structure.QuestBranchImplementation.lambda$finishPlayerStage$4(QuestBranchImplementation.java:211) ~[?:?]
        at fr.skytasul.quests.structure.QuestBranchImplementation.endStage(QuestBranchImplementation.java:267) ~[?:?]
        at fr.skytasul.quests.structure.QuestBranchImplementation.finishPlayerStage(QuestBranchImplementation.java:204) ~[?:?]
        at fr.skytasul.quests.structure.StageControllerImplementation.lambda$finishStage$0(StageControllerImplementation.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Software**
BeautyQuests version: 1.0.3
Game version: 1.16.5
Server version: 1.16.5
Server type (e.i. PaperSpigot): PaperSpigot
Are you using a protocol hack (like ViaVersion)? No

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
That's a bug with versions prior than 1.20. I'll fix asap.

**Comment by rainbowboii** [comment]
> That's a bug with versions prior than 1.20. I'll fix asap.

Latest 1.20.1 Paper same issue

**Comment by SkytAsul** [comment]
1.20.1 is not supported. Please try again with 1.20.4,5,6 or 1.21 using latest dev build from here https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/
