### ISSUE TITLE
Particles 1.20.1 

### ISSUE THREAD

**Issue by rainbowboii** [SkytAsul/BeautyQuests#326]
**Describe the bug**	
Particle error in console 1.20.1

**Reproduction**
Start any core from "software" description 1.20.1 core with BeautyQuests 

**Screenshots, error messages**
[24Jun2024 14:06:59.193] [Server thread/WARN] [BeautyQuests/]: Loading of start particles failed: Invalid particle, color or shape.
java.lang.IllegalArgumentException: No enum constant org.bukkit.Particle.DUST
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?] {re:mixin,re:mixin}
	at org.bukkit.Particle.valueOf(Particle.java:1) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:classloading}
	at fr.skytasul.quests.utils.ParticleEffect.deserialize(ParticleEffect.java:129) ~[?:?] {}
	at fr.skytasul.quests.QuestsConfigurationImplementation.loadParticles(QuestsConfigurationImplementation.java:166) ~[?:?] {}
	at fr.skytasul.quests.QuestsConfigurationImplementation.init(QuestsConfigurationImplementation.java:114) ~[?:?] {}
	at fr.skytasul.quests.BeautyQuests.loadConfigParameters(BeautyQuests.java:384) ~[?:?] {}
	at fr.skytasul.quests.BeautyQuests.onEnable(BeautyQuests.java:150) ~[?:?] {}
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:logger,pl:arclight_implementer:A,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:logger,pl:arclight_implementer:A,re:mixin}
	at net.minecraft.server.MinecraftServer.handler$zcl000$arclight$enablePlugins(MinecraftServerMixin.java:2138) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2029) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin,re:mixin}
[24Jun2024 14:06:59.194] [Server thread/INFO] [BeautyQuests/]: Loaded start particles: REDSTONE in shape POINT with color R255 G255 B0
[24Jun2024 14:06:59.194] [Server thread/WARN] [BeautyQuests/]: Loading of talk particles failed: Invalid particle, color or shape.
java.lang.IllegalArgumentException: No enum constant org.bukkit.Particle.HAPPY_VILLAGER
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?] {re:mixin,re:mixin}
	at org.bukkit.Particle.valueOf(Particle.java:1) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:classloading}
	at fr.skytasul.quests.utils.ParticleEffect.deserialize(ParticleEffect.java:129) ~[?:?] {}
	at fr.skytasul.quests.QuestsConfigurationImplementation.loadParticles(QuestsConfigurationImplementation.java:166) ~[?:?] {}
	at fr.skytasul.quests.QuestsConfigurationImplementation.init(QuestsConfigurationImplementation.java:116) ~[?:?] {}
	at fr.skytasul.quests.BeautyQuests.loadConfigParameters(BeautyQuests.java:384) ~[?:?] {}
	at fr.skytasul.quests.BeautyQuests.onEnable(BeautyQuests.java:150) ~[?:?] {}
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:logger,pl:arclight_implementer:A,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:logger,pl:arclight_implementer:A,re:mixin}
	at net.minecraft.server.MinecraftServer.handler$zcl000$arclight$enablePlugins(MinecraftServerMixin.java:2138) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2029) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin,re:mixin}
[24Jun2024 14:06:59.194] [Server thread/INFO] [BeautyQuests/]: Loaded talk particles: VILLAGER_HAPPY in shape BAR
[24Jun2024 14:06:59.194] [Server thread/WARN] [BeautyQuests/]: Loading of next particles failed: Invalid particle, color or shape.
java.lang.IllegalArgumentException: No enum constant org.bukkit.Particle.SMOKE
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?] {re:mixin,re:mixin}
	at org.bukkit.Particle.valueOf(Particle.java:1) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:classloading}
	at fr.skytasul.quests.utils.ParticleEffect.deserialize(ParticleEffect.java:129) ~[?:?] {}
	at fr.skytasul.quests.QuestsConfigurationImplementation.loadParticles(QuestsConfigurationImplementation.java:166) ~[?:?] {}
	at fr.skytasul.quests.QuestsConfigurationImplementation.init(QuestsConfigurationImplementation.java:119) ~[?:?] {}
	at fr.skytasul.quests.BeautyQuests.loadConfigParameters(BeautyQuests.java:384) ~[?:?] {}
	at fr.skytasul.quests.BeautyQuests.onEnable(BeautyQuests.java:150) ~[?:?] {}
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:logger,pl:arclight_implementer:A,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23171!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:logger,pl:arclight_implementer:A,re:mixin}
	at net.minecraft.server.MinecraftServer.handler$zcl000$arclight$enablePlugins(MinecraftServerMixin.java:2138) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2029) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:reterraforged-common.mixins.json:MixinMinecraftServer,pl:mixin:APP:reterraforged-forge.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin,re:mixin}

**Software**
BeautyQuests version: 1.0.3
Game version: 1.20.1
Server version: arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5
Server type (e.i. PaperSpigot): Hybrid
Are you using a protocol hack (like ViaVersion)? No

**Additional context (optional)**
Tested at Mohist 1.20.1 565, Mohist 1.20.1 722, arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5 and paper 1.20.1.

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by EnderGriefeur99** [comment]
we dont support modded server btw, for 1.21 use 1.0.4 dev build #408
