### ISSUE TITLE
Paper 1.20.1 Particles issue

### ISSUE THREAD

**Issue by rainbowboii** [SkytAsul/BeautyQuests#327]
**Describe the bug**	
Particles console Error

**Reproduction**
Install any Paper 1.20.1 with BeautyQuests 1.0.3 and start server for issue

**Screenshots, error messages**
[19:21:53 WARN]: [BeautyQuests] Loading of start particles failed: Invalid particle, color or shape.
java.lang.IllegalArgumentException: No enum constant org.bukkit.Particle.DUST
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at org.bukkit.Particle.valueOf(Particle.java:9) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at fr.skytasul.quests.utils.ParticleEffect.deserialize(ParticleEffect.java:129) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.QuestsConfigurationImplementation.loadParticles(QuestsConfigurationImplementation.java:166) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.QuestsConfigurationImplementation.init(QuestsConfigurationImplementation.java:114) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.BeautyQuests.loadConfigParameters(BeautyQuests.java:384) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.BeautyQuests.onEnable(BeautyQuests.java:150) ~[beautyquests-1.0.3(1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-192]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-192]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-192]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-192]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[19:21:53 INFO]: [BeautyQuests] Loaded start particles: REDSTONE in shape POINT with color R255 G255 B0
[19:21:53 WARN]: [BeautyQuests] Loading of talk particles failed: Invalid particle, color or shape.
java.lang.IllegalArgumentException: No enum constant org.bukkit.Particle.HAPPY_VILLAGER
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at org.bukkit.Particle.valueOf(Particle.java:9) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at fr.skytasul.quests.utils.ParticleEffect.deserialize(ParticleEffect.java:129) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.QuestsConfigurationImplementation.loadParticles(QuestsConfigurationImplementation.java:166) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.QuestsConfigurationImplementation.init(QuestsConfigurationImplementation.java:116) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.BeautyQuests.loadConfigParameters(BeautyQuests.java:384) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.BeautyQuests.onEnable(BeautyQuests.java:150) ~[beautyquests-1.0.3(1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-192]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-192]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-192]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-192]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[19:21:53 INFO]: [BeautyQuests] Loaded talk particles: VILLAGER_HAPPY in shape BAR
[19:21:53 WARN]: [BeautyQuests] Loading of next particles failed: Invalid particle, color or shape.
java.lang.IllegalArgumentException: No enum constant org.bukkit.Particle.SMOKE
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at org.bukkit.Particle.valueOf(Particle.java:9) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at fr.skytasul.quests.utils.ParticleEffect.deserialize(ParticleEffect.java:129) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.QuestsConfigurationImplementation.loadParticles(QuestsConfigurationImplementation.java:166) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.QuestsConfigurationImplementation.init(QuestsConfigurationImplementation.java:119) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.BeautyQuests.loadConfigParameters(BeautyQuests.java:384) ~[beautyquests-1.0.3(1).jar:?]
        at fr.skytasul.quests.BeautyQuests.onEnable(BeautyQuests.java:150) ~[beautyquests-1.0.3(1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-192]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-192]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-192]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-192]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-192]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Software**
BeautyQuests version: 1.0.3
Game version: 1.20.1
Server version: Paper version git-Paper-192 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a856073)
Server type (e.i. PaperSpigot): PaperSpigot
Are you using a protocol hack (like ViaVersion)? No

**Additional context (optional)**
Vanilla

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by EnderGriefeur99** [comment]
check ticket #326

**Comment by rainbowboii** [comment]
> check ticket #326

I use vanilla and 1.20.1, not 1.21

**Comment by mani1232** [comment]
im have same error on paper 1.20.1

**Comment by EnderGriefeur99** [comment]
just set the write type of particles

**Comment by mani1232** [comment]
> just set the right type of particles

This is default config

**Comment by EnderGriefeur99** [comment]
please send your config file

**Comment by mani1232** [comment]
[config.txt](https://github.com/user-attachments/files/15959157/config.txt)

**Comment by mani1232** [comment]
![image](https://github.com/SkytAsul/BeautyQuests/assets/70480001/2004cdda-ca8e-4873-8411-8210f74f5d7b)
Paper have it

**Comment by EnderGriefeur99** [comment]
pastebin please

**Comment by mani1232** [comment]
I'd fix it myself, but you're using a lot of local dependencies.

**Comment by EnderGriefeur99** [comment]
in 1.20.1 it's -> [VILLAGER_HAPPY](https://helpch.at/docs/1.20.1/org/bukkit/Particle.html#VILLAGER_HAPPY)

**Comment by mani1232** [comment]
![image](https://github.com/SkytAsul/BeautyQuests/assets/70480001/6b5a7b9a-5ef1-4dee-965a-66d02a0d008d)
dust?

**Comment by mani1232** [comment]
![image](https://github.com/SkytAsul/BeautyQuests/assets/70480001/be91b129-9f0b-4b43-abf4-6a8341909821)
smoke?

**Comment by mani1232** [comment]
ok, thx

**Comment by ipaulocesar** [comment]
```javascript
# Particles shown on a NPC when the player can start the quest
start:
  enabled: true
  particleEffect: REDSTONE
  particleColor:
    RED: 255
    BLUE: 0
    GREEN: 255
  particleShape: point
# Particles shown on the NPC to which the player has to talk
talk:
  enabled: true
  particleEffect: VILLAGER_HAPPY
  particleColor:
    RED: 255
    BLUE: 0
    GREEN: 255
  particleShape: bar
# Particles shown when the player finish a stage of a quest
next:
  enabled: true
  particleEffect: SMOKE_NORMAL
  particleColor:
    RED: 255
    BLUE: 0
    GREEN: 255
  particleShape: spot
```

**Comment by SkytAsul** [comment]
Yeah Spigot renamed everything without maintaining backward compatibility, sorry about that
