### ISSUE TITLE
The player will see this after completing the mission, scoreboards won’t disappear

### ISSUE THREAD

**Issue by SuMMeRHoTOxo** [SkytAsul/BeautyQuests#330]
**Describe the bug**	
The player will see this after completing the mission, scoreboards won’t disappear

**Reproduction**
The player will see this after completing the mission

**Screenshots, error messages**
```
[03:10:08 WARN]: [BeautyQuests] Task #46158 for BeautyQuests v1.0.3 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.World.spawn(org.bukkit.Location, java.lang.Class, java.util.function.Consumer)'
        at fr.skytasul.quests.utils.QuestUtils.lambda$spawnFirework$4(QuestUtils.java:157) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.utils.QuestUtils.runOrSync(QuestUtils.java:82) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.utils.QuestUtils.spawnFirework(QuestUtils.java:151) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.structure.QuestImplementation.lambda$finish$15(QuestImplementation.java:505) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.utils.QuestUtils.runOrSync(QuestUtils.java:82) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.structure.QuestImplementation.lambda$finish$16(QuestImplementation.java:493) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.structure.QuestImplementation.finish(QuestImplementation.java:519) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.structure.QuestBranchImplementation.lambda$finishPlayerStage$4(QuestBranchImplementation.java:211) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.structure.QuestBranchImplementation.endStage(QuestBranchImplementation.java:267) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.structure.QuestBranchImplementation.finishPlayerStage(QuestBranchImplementation.java:204) ~[beautyquests-1.0.3.jar:?]
        at fr.skytasul.quests.structure.StageControllerImplementation.lambda$finishStage$0(StageControllerImplementation.java:75) ~[beautyquests-1.0.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]```

![螢幕擷取畫面 2024-07-23 031935](https://github.com/user-attachments/assets/236a980d-9cac-41a8-b3ee-378590077361)
![螢幕擷取畫面 2024-07-23 031949](https://github.com/user-attachments/assets/f174c2a6-69ff-4dde-a678-4f14f65b85e5)

**Software**
BeautyQuests version: 1.0.3
Game version: 1.20.1
Server version: 1.20.1
Server type (e.i. PaperSpigot): paper
Are you using a protocol hack (like ViaVersion)?  ViaVersion

**Comment by SkytAsul** [comment]
This is an issue on old Paper versions. Please either update to 1.21 or disable fireworks in config.yml.
