### ISSUE TITLE
task 2893

### ISSUE THREAD

**Issue by fr3d3lin** [SkytAsul/BeautyQuests#333]
je parle francais :D 

**Describe the bug**	
quand un joueur bedrock se connect au serveur (geyser)

**Reproduction**
connect un joueur bedrock

**Software**
BeautyQuests version: 1.0.3
Game version: what?
Server version: 1.17.1
Server type: paper (last of 1.17.1)
Are you using a protocol hack ViaVersion, floodgate

**Additional context (optional)**

[16:22:18] [Craft Scheduler Thread - 11 - BeautyQuests/WARN]: [BeautyQuests] Plugin BeautyQuests v1.0.3 generated an exception while executing task 2893
java.lang.NoClassDefFoundError: fr/skytasul/quests/players/AbstractPlayersManager$AccountFetchRequest
at fr.skytasul.quests.players.AbstractPlayersManager.tryLoad(AbstractPlayersManager.java:161) ~[BeautyQuests.jar:?]
at fr.skytasul.quests.players.AbstractPlayersManager.lambda$loadPlayer$1(AbstractPlayersManager.java:142) ~[BeautyQuests.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: fr.skytasul.quests.players.AbstractPlayersManager$AccountFetchRequest
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-411]
at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
... 8 more

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

je parle francais :D

**Comment by SkytAsul** [comment]
Quand un joueur normal se connecte ça ne fait pas d'erreur ?

**Comment by SkytAsul** [comment]
Salut ! Y a-t-il du nouveau ?

**Comment by fr3d3lin** [comment]
Non, je n'ai pas remarqué si le bug apparaissait encore.

**Comment by fr3d3lin** [comment]
On peut fermer le post, jen ferais un nouveau si je vois qqch 👍🏻
