### ISSUE TITLE
Error while trying to reset a quest from player

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#47]
using this according to quest help, I should be able to reset quest id 2. 

```java

[08:26:31 INFO]: madtomic issued server command: /quest resetplayer Zitrakus 2
[08:26:31 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'quest' in plugin BeautyQuests v0.14_PRE7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[paper-1.12.2.jar:git-Paper-71113273]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[paper-1.12.2.jar:git-Paper-71113273]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:632) ~[paper-1.12.2.jar:git-Paper-71113273]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1473) ~[paper-1.12.2.jar:git-Paper-71113273]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1278) ~[paper-1.12.2.jar:git-Paper-71113273]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[paper-1.12.2.jar:git-Paper-71113273]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[paper-1.12.2.jar:git-Paper-71113273]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paper-1.12.2.jar:git-Paper-71113273]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[paper-1.12.2.jar:git-Paper-71113273]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[paper-1.12.2.jar:git-Paper-71113273]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[paper-1.12.2.jar:git-Paper-71113273]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[paper-1.12.2.jar:git-Paper-71113273]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[paper-1.12.2.jar:git-Paper-71113273]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at fr.skytasul.quests.commands.CommandsManager.onCommand(CommandsManager.java:89) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[paper-1.12.2.jar:git-Paper-71113273]
        ... 15 more
```

**Comment by madtomic** [comment]
I figured it out.
