### ISSUE TITLE
<bug> Utilisation de commandes en tant que reward avec PermissionsEX

### ISSUE THREAD

**Issue by Darqbit** [SkytAsul/BeautyQuests#52]
**Describe the bug**	

J'essaye de me servir des permissions pour faire une variable booléenne afin d'interdire de compléter plusieures quêtes en même temps. 

Enlever ou ajouter une permission relative a {PLAYER} en utilisant le reward de fin de quête (commande avec ou sans mode console)

**To Reproduce**	
Un joueur avec une permissions "choixQuetes" de permissionsEX.
Le joueur remplit la quête sur le PNJ qui doit reward la commande "pex user {PLAYER} remove choixQuetes"
La permission n'est pas enlevée et génère cette erreure une fois la quête remplie :
 
[23:25:06] [Async Chat Thread - #31/ERROR]: [BeautyQuests] Error when giving reward commandReward to fredoo1
[23:25:06] [Async Chat Thread - #31/WARN]: java.lang.IllegalStateException: Asynchronous command dispatch!
[23:25:06] [Async Chat Thread - #31/WARN]:      at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[23:25:06] [Async Chat Thread - #31/WARN]:      at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:700)
[23:25:06] [Async Chat Thread - #31/WARN]:      at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:619)
[23:25:06] [Async Chat Thread - #31/WARN]:      at fr.skytasul.quests.rewards.CommandReward.give(CommandReward.java:30)
[23:25:06] [Async Chat Thread - #31/WARN]:      at fr.skytasul.quests.utils.Utils.giveRewards(Utils.java:103)
[23:25:06] [Async Chat Thread - #31/WARN]:      at fr.skytasul.quests.Quest$3.run(Quest.java:451)
[23:25:06] [Async Chat Thread - #31/WARN]:      at fr.skytasul.quests.Quest.finish(Quest.java:474)
[23:25:06] [Async Chat Thread - #31/WARN]:      at fr.skytasul.quests.stages.StageManager$1.run(StageManager.java:163)
[23:25:06] [Async Chat Thread - #31/WARN]:      at fr.skytasul.quests.stages.StageManager.next(StageManager.java:174)
[23:25:06] [Async Chat Thread - #31/WARN]:      at fr.skytasul.quests.api.stages.AbstractStage.finishStage(AbstractStage.java:120)
[23:25:06] [Async Chat Thread - #31/WARN]:      at fr.skytasul.quests.stages.StageChat.check(StageChat.java:60)
[23:25:06] [Async Chat Thread - #31/WARN]:      at fr.skytasul.quests.stages.StageChat.onTchat(StageChat.java:48)
[23:25:06] [Async Chat Thread - #31/WARN]:      at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
[23:25:06] [Async Chat Thread - #31/WARN]:      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:25:06] [Async Chat Thread - #31/WARN]:      at java.lang.reflect.Method.invoke(Method.java:498)
[23:25:06] [Async Chat Thread - #31/WARN]:      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305)
[23:25:06] [Async Chat Thread - #31/WARN]:      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:25:06] [Async Chat Thread - #31/WARN]:      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[23:25:06] [Async Chat Thread - #31/WARN]:      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482)
[23:25:06] [Async Chat Thread - #31/WARN]:      at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1558)
[23:25:06] [Async Chat Thread - #31/WARN]:      at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1496)
[23:25:06] [Async Chat Thread - #31/WARN]:      at net.minecraft.server.v1_13_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
[23:25:06] [Async Chat Thread - #31/WARN]:      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:25:06] [Async Chat Thread - #31/WARN]:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:25:06] [Async Chat Thread - #31/WARN]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:25:06] [Async Chat Thread - #31/WARN]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Expected behavior**	
Je pensais que commandes de fin de quête pouvais executer une commande d'un autre plugin.

**Screenshots, errors**	
J'ai mis le code d'erreur de la console

**Softwares (please complete the following information):**	
[22:00:04] [INFO]: Enabling BeautyQuests v0.13.2
[22:00:04] [INFO]: MythicMobs isn't loaded on this server. Some features are not enabled because of that.
[22:00:04] [INFO]: Vault isn't loaded on this server. Some features are not enabled because of that.
[22:00:04] [INFO]: PlaceHolderAPI isn't loaded on this server. Some features are not enabled because of that.
[22:00:04] [INFO]: HolographicDisplays isn't loaded on this server. Some features are not enabled because of that.
[22:00:04] [INFO]: Jobs isn't loaded on this server. Some features are not enabled because of that.
[22:00:04] [INFO]: Factions isn't loaded on this server. Some features are not enabled because of that.
[22:00:04] [INFO]: Loaded valid version v1_13_R2
[22:00:04] [INFO]: Loaded language file fr.yml

**Additional context**	
Spigot 1.13.2 R02 

++ : Il est possible que j'ai sur estimé ton plugin, en tout cas super boulot on kiff a plusieurs à essayer d'en retirer le meilleur :) Merci beaucoup pour le temps passé dessus :) :+1:

**Comment by SkytAsul** [comment]
C'est un bug que je n'avais pas prévu, en effet. Je m'occupe de le régler 😉

**Comment by Darqbit** [comment]
Heyyyy t'es méga réactif super :)

**Comment by SkytAsul** [comment]
https://github.com/SkytAsul/BeautyQuests/commit/7de5253c1c804667ade42e2d99e9682a6da7f615
