### ISSUE TITLE
<bug> Error occurs when trying to edit the type of a NPC in 1.14

### ISSUE THREAD

**Issue by Vainock** [SkytAsul/BeautyQuests#69]
**Describe the bug**	
(title)

**Reproduction**
(title)

**Expected behavior**
That I can edit the type of the NPC.

**Screenshots, error messages**
Error:
```
[21:15:14] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BeautyQuests v0.15
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2158) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createInventory(CraftServer.java:1542) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.Bukkit.createInventory(Bukkit.java:1006) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at fr.skytasul.quests.gui.misc.EntityTypeGUI.open(EntityTypeGUI.java:55) ~[?:?]
	at fr.skytasul.quests.gui.Inventories.create(Inventories.java:37) ~[?:?]
	at fr.skytasul.quests.gui.npc.NPCGUI.onClick(NPCGUI.java:97) ~[?:?]
	at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:60) ~[?:?]
	at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:90) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	... 17 more
```

**Softwares**
BeautyQuests version: 0.15
Game version: 1.14
Server version: 1.14
Server type (e.g. PaperSpigot): Spigot
Are you using a protocol hack (like ViaVersion)? No

**Comment by SkytAsul** [comment]
Oh I was not expecting Mojang staff add so many entities that my inventories can't even handle x)

**Comment by SkytAsul** [comment]
Fixed https://github.com/SkytAsul/BeautyQuests/commit/a278b607a9be555995bfb7628e344e1dc0aa2dae
