### ISSUE TITLE
Unable to create NPC

### ISSUE THREAD

**Issue by Vainock** [SkytAsul/BeautyQuests#94]
**Describe the bug**	
When validating the creation of a NPC, a big error in the console occurs and everything stops working.

**Softwares**
BeautyQuests version: v0.16_BUILD25
Game version: 1.14.4
Server version: 1.14.4
Server type (e.g. PaperSpigot): Spigot
Are you using a protocol hack (like ViaVersion)? No

**Error**

```
[14:41:14] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[14:41:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:41:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[14:41:14] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[14:41:14] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[14:41:14] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:47)
[14:41:14] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[14:41:14] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[14:41:14] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:234)
[14:41:14] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:210)
[14:41:14] [Server thread/WARN]: 	at fr.skytasul.quests.gui.npc.NPCGUI.onClick(NPCGUI.java:106)
[14:41:14] [Server thread/WARN]: 	at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:66)
[14:41:14] [Server thread/WARN]: 	at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:100)
[14:41:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:41:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:41:14] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:41:14] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:41:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[14:41:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:41:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[14:41:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2133)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820)
[14:41:14] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:41:14] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.Entity.<init>(Entity.java:199)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityLiving.<init>(EntityLiving.java:144)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityInsentient.<init>(EntityInsentient.java:56)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityCreature.<init>(EntityCreature.java:10)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityAgeable.<init>(EntityAgeable.java:14)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityVillagerAbstract.<init>(EntityVillagerAbstract.java:33)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityVillager.<init>(EntityVillager.java:62)
[14:41:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityVillager.<init>(EntityVillager.java:58)
[14:41:14] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.VillagerController$EntityVillagerNPC.<init>(VillagerController.java:57)
[14:41:14] [Server thread/WARN]: 	... 34 more
[14:41:14] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BeautyQuests v0.16_BUILD25
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2133) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:34) ~[?:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:234) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:210) ~[?:?]
	at fr.skytasul.quests.gui.npc.NPCGUI.onClick(NPCGUI.java:106) ~[?:?]
	at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:66) ~[?:?]
	at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:100) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	... 17 more
```

**Comment by SkytAsul** [comment]
This error belongs to the Citizens issues section, make sure you're using the latest Citizens dev build.
